server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 20

spring:
  datasource:
    url: ${DATABASE_URL}
    hikari:
      maximum-pool-size: 3
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update